stockanalysis/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='accounts/thanks.html'), name = 'logout'),
]

stockanalysis/stockanalysis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from stocksapp import views
from accounts import views as accounts_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^stocksapp/', include('stocksapp.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r"^accounts/", include("django.contrib.auth.urls")),

]

stockanalysis/stocksapp/urls.py
from django.conf.urls import url
from stocksapp import views
app_name = 'stocksapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'home'),
    url(r'^upload/', views.FileUploadView.as_view(), name='upload_csv'),
    url(r'^company_tickers/', views.company_tickers_view, name='company_tickers'),
    url(r'^company_overview/(?P<pk>\d+)/', views.company_overview, name='company_overview'),
    url(r'^live_ticker_pricing/', views.live_ticker_price, name='live_ticker_price'),
    url(r'^purge_database/', views.purge_database, name='purge_database'),
    url(r'^stock_comparison/', views.stock_comparison, name='stock_comparison'),
    url(r'^get_json/(?P<pk>\d+)', views.get_stock_data, name='stock_data'),
    url(r'^test/', views.TestView.as_view(), name='json'),
    url(r'^portfolio/', views.PortfolioList.as_view(), name='portfolio_list'),
    url(r'^test_portfolio_insert/', views.test_portfolio_insert, name='portfolio_insert'),
    url(r'^create_portfolio/', views.CreatePortfolio, name='create_portfolio'),
    url(r'^check_portfolio_name/(?P<portfolio_name>\w+)', views.check_portfolio_name, name='check_portfolio_name'),
    url(r'^portfolio_performance/(?P<pk>\w+)', views.portfolio_performance, name='portfolio_performance'),
    url(r'^portfolio_performance_page/(?P<pk>\w+)', views.portfolio_performance_page, name='portfolio_performance_page'),
    url(r'^company_comparison_endpoint/', views.company_comparison_service, name='company_comparison_service'),

]

stockanalysis/stocksapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class Company(models.Model):
    id = models.AutoField(primary_key = True)
    ticker = models.CharField(max_length=20)
    company_name = models.CharField(max_length=200)
    description = models.TextField()
    gics_sector = models.CharField(max_length=200)
    gics_industry = models.CharField(max_length=200)
    gics_industry_group = models.CharField(max_length=200)
    gics_sub_industry_group = models.CharField(max_length=200)


    def __str__(self):
        return str(self.id)

class StockData(models.Model):
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    date = models.DateField()
    closing_price = models.FloatField()
    volume = models.BigIntegerField()

    def __str__(self):
        return 'Stocks-<company'+str(self.company_id)+'>-'+str(self.date)


User = get_user_model()

class Portfolio(models.Model):
    portfolio_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    portfolio_name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.portfolio_id)


class PortfolioCompanies(models.Model):
    portfolio_id = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    percentage = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(0)])

    def __str__(self):
        return str(self.portfolio_id)

stockanalysis/stocksapp/forms.py
from django import forms

class UploadCSVForm(forms.Form):
    select_type = forms.ChoiceField(choices=[('Company Data', 'company data'),('Stocks Data', 'stocks data')])
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

stockanalysis/stocksapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import pandas as pd
import os
import json
from django.conf import settings
from stocksapp.models import Company, StockData, PortfolioCompanies, Portfolio
from django.views.generic.edit import FormView
from datetime import datetime
from .forms import UploadCSVForm
from django.views.generic import TemplateView, DetailView, DeleteView, ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
import numpy as np
from scipy import stats
# Create your views here.

class IndexView(TemplateView):
    ''' Class based view for Index page '''
    template_name = 'stocksapp/index.html'


class FileUploadView(FormView, SuccessMessageMixin):
    ''' Controller for uploading files'''
    form_class = UploadCSVForm
    template_name = 'stocksapp/upload_csv.html'
    success_url = '/'
    success_message = "File data uploaded to database successfully"
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        files = request.FILES.getlist('file')
        if form.is_valid():
            csv_type = form.cleaned_data['select_type']
            for f in files:
                self.process_file_into_database(f, csv_type)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def process_file_into_database(self, file, csv_type):
        ''' A method to iterate through each row in csv and fill in database '''
        if csv_type == 'Company Data' or csv_type == 'company data':
            df = pd.read_csv(file)
            for index, row in df.iterrows():
                company_record = Company(index+1,row['Ticker'],row['Name'],row['Description'],row['GICS Sector'],row['GICS industry']
                                        ,row['GICS Industry group'],row['GICS Sub Industry Group'])
                company_record.save()
        elif csv_type == 'Stocks Data' or csv_type == 'stocks data':
            df_stocks = pd.read_csv(file)

            # Go through each stock and save it appropriately
            # StockData.objects.all().delete()
            for index, row in df_stocks.iterrows():
                c_id = Company.objects.filter(ticker__icontains=str(file).split('.')[0])
                stock_record = StockData(company_id=c_id[0], date = datetime.strptime(row['Date'].strip(), "%m/%d/%Y").date(), closing_price=row['PX_LAST'],
                                        volume=row['PX_VOLUME'])
                stock_record.save()

def company_tickers_view(request):
    ''' Returns all tickers from the database '''
    company_objects = Company.objects.all() #Return all company objects for tickers
    return render(request, 'stocksapp/company_details.html', {'company_objects':company_objects})


def company_overview(request,pk):
    ''' Gets required attributs from the Databse and sends to the view'''
    company = Company.objects.filter(pk=pk)[0]  # Get company object
    # stocks = StockData.objects.filter(company_id=pk)
    # related_data = []
    # for stock_item in stocks:
    #     related_data.append([(str(stock_item.date).replace('-','/')), stock_item.closing_price, stock_item.volume])
    data = {'name':company.company_name, 'company_id':pk,'description':company.description,
            'gics_sector':company.gics_sector, 'gics_industry':company.gics_industry,
            'gics_industry_group':company.gics_industry_group,
            'gics_sub_industry_group':company.gics_sub_industry_group}
    return JsonResponse(data)

def purge_database(request):
    ''' Caution!: Deletes all items from the database. Only valid on POST request '''
    if request.method == 'POST':
        #Purge the database
        # Portfolio.objects.all().delete()
        # PortfolioCompanies.objects.all().delete()
        # Company.objects.all().delete()
        # StockData.objects.all().delete()
        return redirect('/')

    return HttpResponse('error')

class TestView(TemplateView):
    template_name = 'stocksapp/line_chart.html'

def get_stock_data(request, pk):
    ''' Returns json object for all stocks for a given company'''
    stocks = StockData.objects.filter(company_id=pk)
    data = []
    for stock_item in stocks:
        data.append([(str(stock_item.date).replace('-','/')), stock_item.closing_price, stock_item.volume])

    return HttpResponse(json.dumps(data))


class PortfolioList(ListView, LoginRequiredMixin):
    ''' Controller to view all available portfolios specific to the user'''
    model = Portfolio
    template_name = 'stocksapp/portfolio_list.html'
    def get_queryset(self):
        if self.request.user.is_authenticated():
            return Portfolio.objects.filter(user = self.request.user)   #Get portfolio for current user
        else:
            return None


def test_portfolio_insert(request):
    '''test method'''
    data = {}
    name = ''
    if request.method == 'POST':
        data = request.POST.get('custom_portfolio') #Get values from ID in HTML
        name = request.POST.get('portfolioName')
    InsertPortfolioService(json.loads(data), request.user,name)
    return redirect('../portfolio')


def InsertPortfolioService(portfolio_dictionary, user_obj, name):
    ''' Inserting portfolio configuration onto the database '''
    portfolio_object = Portfolio(user=user_obj, portfolio_name=name)
    portfolio_object.save()
    for ticker, weight in portfolio_dictionary.items():
        # Get company id for the given ticker
        company_object = Company.objects.filter(ticker__icontains=ticker)[0]
        # now save details to portfolio PortfolioCompanies
        portfolio_companies = PortfolioCompanies(portfolio_id=portfolio_object,company_id=company_object,percentage=weight)
        portfolio_companies.save()

def CreatePortfolio(request):
    ''' Redirect to Create Portfolio page with ticker values '''
    template_name = 'stocksapp/create_portfolio.html'
    tickers = list(Company.objects.values_list('ticker',flat=True))
    result = ','.join(tickers)
    return render(request, template_name, {'tickers_list':result})


def check_portfolio_name(request, portfolio_name):
    return HttpResponse(len(list(Portfolio.objects.filter(user=request.user, portfolio_name__iexact=portfolio_name))) == 0)

def portfolio_performance(request, pk):
    ''' Calculates the performance of the portfolio over a date range'''
    portfolio_data = PortfolioCompanies.objects.filter(portfolio_id=pk)
    percentage_data = []    #get weights for every company in portfolio
    percentage_ticker = [] #Get tickers for all companies in the portfolio
    for percentage in portfolio_data:
        #Get ticker
        percentage_ticker.append(Company.objects.filter(id=percentage.company_id.id).values_list('ticker', flat=True)[0])
        percentage_data.append(percentage.percentage)


    portfolio_split = {}
    for x, y in zip(percentage_ticker, percentage_data):
        portfolio_split[x] = y


    stocks_data = []
    stocks_dates = StockData.objects.filter(company_id = portfolio_data[0].company_id, date__gte=datetime.strptime("2016-12-31", "%Y-%m-%d").date()).order_by('date').values_list('date', flat=True)
    final_data = []
    for item in portfolio_data:
        stocks_for_company = StockData.objects.filter(company_id = item.company_id, date__gte=datetime.strptime("2016-12-31", "%Y-%m-%d").date()).order_by('date').values_list('closing_price', flat=True)
        stocks_for_company = list(stocks_for_company)
        first_day_price = stocks_for_company[0]
        #Calculate percentage change
        stocks_percentage_change = np.around(((np.array(stocks_for_company) - first_day_price)/first_day_price)* 100,decimals=2)
        stocks_percentage_change *= item.percentage/100
        stocks_data.append(stocks_percentage_change)
    my_array = np.zeros(len(stocks_data[0]))
    for x in stocks_data:
        my_array += np.array(x)

    performance_overtime = np.around(my_array, decimals=2).tolist()

    for date, povertime in zip(stocks_dates, performance_overtime):
        final_data.append([str(date).replace('-','/'), povertime])

    finalized_data = {}
    finalized_data['PerformanceOvertime'] = final_data
    finalized_data['Splits'] = portfolio_split

    return HttpResponse(json.dumps(finalized_data))


def portfolio_performance_page(request, pk):
    return render(request, 'stocksapp/portfolio_performance.html', {'portfolioID':pk})

def stock_comparison(request):
    return render(request, 'stocksapp/stock_comparisons.html', {'company_objects':Company.objects.all()})

def company_comparison_service(request):
    ''' Compares the closing prices of 2 companies over a specific date range and Calculates regression '''
    companyA_id = request.GET.get('companyA')
    companyB_id = request.GET.get('companyB')
    tickerA = list(Company.objects.filter(id=companyA_id).values_list('ticker',flat=True))[0]
    tickerB = list(Company.objects.filter(id=companyB_id).values_list('ticker',flat=True))[0]
    date_range = [str(x).replace('-','/') for x in list(StockData.objects.values_list('date', flat=True).distinct())]
    closing_price_companyA = list(StockData.objects.filter(company_id = companyA_id).values_list('closing_price', flat=True))
    closing_price_companyB = list(StockData.objects.filter(company_id = companyB_id).values_list('closing_price', flat=True))
    dataPoints = []
    for x,y in zip(closing_price_companyA, closing_price_companyB):
        dataPoints.append([x,y])

    #Calculate LinearRegression
    slope, intercept, r_value, p_value, std_err = stats.linregress(closing_price_companyA, closing_price_companyB)
    fitted_line = []
    for x in closing_price_companyA:
        fitted_line.append([x, intercept + slope*x])
    #Pass data to the frontend
    #'corr':np.corrcoef(np.array(closing_price_companyA),np.array(closing_price_companyB))

stockanalysis/templates/stocksapp/base.html
<!DOCTYPE html>

{% load staticfiles %}
<head>
      <style>
        .red{
            color: red;
        }
        .green{
            color: green;
        }
      </style>

    <meta charset="utf-8">
    <title>Stock Analysis</title>
    <!-- Latest compiled and minified CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="{% static 'stocksapp/js/app.js' %}"></script>
    <link rel="stylesheet" href="{% static 'stocksapp/css/styles.css' %}"></script>

  </head>
  <body>
    <nav class="navbar navbar-inverse" role="navigation" id="navbar">
        			<div class="container">
                <a class="navbar-brand mynav" href="{% url 'home' %}">Portfolio Manager</a>


                  <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                          <li><a href="{% url 'stocksapp:company_tickers' %}" class="btn btn-simple">Company Overview</a></li>
                          <li><a href="{% url 'stocksapp:stock_comparison' %}" class="btn btn-simple">Stock Comparison Analysis</a></li>
                          <li><a href="{% url 'stocksapp:portfolio_list' %}" class="btn btn-simple">Portfolio</a></li>
                          <li><a href="{% url 'stocksapp:live_ticker_price' %}" class="btn btn-simple">Live Data</a></li>
                          <li><a href="{% url 'stocksapp:upload_csv' %}" class="btn btn-simple">Upload New Files</a></li>
                          <li><a href="#" data-href="{% url 'stocksapp:purge_database' %}" class="btn btn-simple" data-toggle="modal" data-target="#confirm-delete">Purge Database</a></li>
                          <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Logout</a></li>
                          {% else %}

        						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>

                    {% endif %}
        					</ul>

        			</div>
        		</nav>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                </div>

                <div class="modal-body">
                    <p>You are about to delete the entire database, this procedure is irreversible.</p>
                    <p>Do you want to proceed?</p>
                    <p class="debug-url"></p>
                </div>

                <div class="modal-footer">
                    <form id='purgeDatabase' action="{% url 'stocksapp:purge_database' %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger btn-ok">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container portfolio-list">
      {% block portflioList %}

      {% endblock %}
    </div>




  </body>
</html>

stockanalysis/templates/stocksapp/company_details.html
{% extends "stocksapp/base.html" %}

{% block content %}
<br>
<br>

<div class="container">
  <select class="form-control form-control-lg ticker" name="" id='companytickers'>
      <option  value="invalid">Select a company</option>
      {% for object in company_objects %}
        <option  value="{{object.id}}">{{object.ticker}}</option>
      {% endfor %}
  </select>


<div id="stock-chart">

</div>

<br>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h4 id='name' class="lead display-3">Please select a company for its information!</h4>
    <p id='description' class="lead"></p>
    <p id='gics_sector' class="lead"></p>
    <p id='gics_industry' class="lead"></p>
    <p id='gics_industry_group' class="lead"></p>
    <p id='gics_sub_industry_group' class="lead"></p>
  </div>
</div>
</div>

{% endblock %}

stockanalysis/templates/stocksapp/create_portfolio.html
{% extends "stocksapp/base.html" %}

{% block content %}
<input type="hidden" id = 'tickers-list' name="" value="{{tickers_list}}">
<script type='text/javascript'>
            var company_list = $('#tickers-list').val().split(',');
            var i = 0;
            function addFields(){
                // Number of inputs to create
                // Container <div> where dynamic content will be placed
                var container = document.getElementById("container");

                    var row = document.createElement("div");

                    row.className = "col-xs-6"
                    // Create an <input> element, set its type and name attributes
                    var companyName = document.createElement("select");
                    companyName.className = "form-control form-control-lg";
                    companyName.type = "text";
                    companyName.name = "select" + i;
                    companyName.onChange = function (ev) {
                        remove(company_list, companyName.options[companyName.selectedIndex].value);
                    }
                    row.appendChild(companyName);

                    company_list.forEach(function(element) {
                        var el = document.createElement("option");
                        el.textContent = element;
                        el.value = element;
                        companyName.appendChild(el);
                    });

                    // Create an <input> element, set its type and name attributes
                    var percentage = document.createElement("input");
                    percentage.className = "col-xs-6";
                    percentage.type = "number";
                    percentage.name = "percent" + (i);
                    row.appendChild(percentage);

                    i = i +1;

                    var remove = document.createElement("button");
                    remove.type = "button";
                    remove.className = "btn btn-default btn-sm";
                    remove.onclick = function (ev) { container.removeChild(row); };
                    var temp = document.createElement("span");
                    temp.className = "glyphicon glyphicon-remove";
                    remove.appendChild(temp);
                    row.appendChild(remove);

                    row.appendChild(document.createElement("br"));
                    row.appendChild(document.createElement("br"));
                    container.appendChild(row);

            }
        </script>





       <!-- Add your site or application content here -->
        <script src="js/vendor/modernizr-3.5.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>



        <br>
        <br>
        <br>

      <div class="form-group">
        <form id = 'portfolio-create' action="{% url 'stocksapp:portfolio_insert' %}" method='POST'>
            {% csrf_token %}
            Portfolio Name : <input class="form-control" type="text" id="portfolioName" name="portfolioName" required>
            <div id="message"></div>
            </br>
            <button type="button" class="btn btn-primary" onclick="addFields()">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
            <br>
            <br>
            <div id="container"></div>

            <input id="custom_portfolio" name="custom_portfolio" hidden >
            <button type="button" class="btn btn-primary" id="submit_portfolio">Create Portfolio</button>

        </form>

      </div>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#submit_portfolio").on('click', function (e) {
                    e.preventDefault();
                    if($('#portfolioName').val().length == 0){
                      alert('Please mention a name');
                      return;
                    }
                    var arr=[];
                    var percentage = [];
                    var st = {};
                    var total = 0;
                    var flag = false;
                    $("select option:selected").each(function()
                    {
                        if(arr.indexOf($(this).val()) !== -1){
                            alert("Same values selected");
                            flag = true;
                            return;
                        }

                        var temp_percentage = $(this).parent().parent().children('input').val();
                        total += parseInt(temp_percentage);
                        console.log(total);
                        percentage.push(temp_percentage);
                        arr.push($(this).val());

                        st[$(this).val()] = temp_percentage;


                    });
                    if(total != 100 && !flag){
                        alert('Total weights should sum to 100');
                    }
                    else if(!flag){
                      console.log(st);

                      $('#custom_portfolio').val(JSON.stringify(st));
                      $('#portfolio-create').submit();
                    }


                });
            });


            $("#portfolioName").on('keyup',function(){
                if($(this).val().trim().length > 0){
                  $.ajax({url: "../check_portfolio_name/"+$(this).val(), success: function(result){
                          // var message_div  = document.getElementById('message');
                          $('#message').empty();

                          if(result=='True'){

                              $('<p class="green">This portfolio name is available</p>').appendTo($('#message'));
                          }
                          else{
                              $('<p class="red">This portfolio name is not available</p>').appendTo($('#message'));
                          }
                          // var message_div = $('#message').insertAfter()
                      }});
                }
                else{
                  $('#message').empty();
                }

            });


        </script>
{% endblock %}

stockanalysis/templates/stocksapp/index.html
{% extends "stocksapp/base.html" %}


{% block content %}

<div class="jumbotron jumbotron-fluid home-style">
  <div class="container">
    <h1 class="display-3">Stock Analysis & Portfolio Manager</h1>
    <p class="lead">Thank you for using my Portfolio Manager.</p>
    <p class="lead">You can use the Web application to create your custom portfolio for performance analysis</p>
    <p class="lead">You can also compare companies and view live stock prices!</p>
    <p class="lead">The Data is pre-populated. There is a purge database functionality which is disabled for demo purposes</p>
    <p class="lead">Username: kshitijgorde & Password:deccanqueen</p>

  </div>
</div>


{% endblock %}

stockanalysis/templates/stocksapp/line_chart.html
{% extends "stocksapp/base.html" %}


{% block content %}
<!-- <div id="container"></div> -->

<!-- <button id="large">Large</button>
<button id="small">Small</button>
<button id="auto">Auto</button> -->

{% endblock %}

stockanalysis/templates/stocksapp/live_stock_price.html
{% extends "stocksapp/base.html" %}


{% block content %}
<div class="container">
  <h4>Please select a ticker from the list</h4>
  <select class="form-control form-control-lg liveTicker" name="" id='liveTicker'>
      <option value='invalid'>Select Ticker</option>
      {% for object in company_objects %}
        <option  value="{{object.ticker}}">{{object.ticker}}</option>
      {% endfor %}
  </select>
<br>
<br>
  <div id="live-stock-graph">

  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Loading Live Data</h4>
      </div>
      <div class="modal-body">
        Your Data will load shortly. Please wait!
      </div>
    </div>
  </div>
</div>





{% endblock %}

stockanalysis/templates/stocksapp/portfolio_list.html
{% extends "stocksapp/base.html" %}

{% block portflioList %}

  {% if portfolio_list %}
        <table class='table table-dark table-striped table-bordered table-hover'>
                    <thead class='thead-light'>
                      <tr>
                        <th scope="col">Portfolio Name</th>
                      </tr>
                    </thead>


                    {% for portfolio in portfolio_list %}
                    <tr>
                      <td scope="row"><a href="{% url 'stocksapp:portfolio_performance_page' pk=portfolio.portfolio_id%}">{{portfolio.portfolio_name}}</a></td>
                    </tr>
                    {% endfor %}
          </table>
  {% else %}
    <h2>You have no saved portfolios.</h2>
  {% endif %}

  <a class='btn btn-lg btn-primary' href="{% url 'stocksapp:create_portfolio' %}">Create New Portfolio</a>
{% endblock %}

stockanalysis/templates/stocksapp/stock_comparisons.html
{% extends "stocksapp/base.html" %}

{% block content %}
<div class="container">

  <h3>Please select two tickers</h3>
  <div class="row">
    <div class="col-xs-6">
      <select class="form-control form-control-lg col-xs-6 ticker-analysis-companyA" name="" id='tickerA'>
          <option value='invalid'>Select Ticker</option>
          {% for object in company_objects %}
            <option  value="{{object.id}}">{{object.ticker}}</option>
          {% endfor %}
      </select>
    </div>

    <div class="col-xs-6">
      <select class="form-control form-control-lg tickerB" name="" id='tickerB'>
          <option value='invalid'>Select Ticker</option>
          {% for object in company_objects %}
            <option  value="{{object.id}}">{{object.ticker}}</option>
          {% endfor %}
      </select>
    </div>


  </div>



  <div class="container" >
    <p id="company-details"></p>
  </div>

<div id="stock-chart-comparisons">

</div>
</div>

{% endblock %}

stockanalysis/templates/stocksapp/upload_csv.html
{% extends "stocksapp/base.html" %}
{% load bootstrap3 %}

{% block content %}
<h2>Upload New Data</h2>
<p class="lead">The CSV format for Company data is:[Ticker, Name, Description, Sector, Industry, IndustryGroup, SubIndustryGroup]</p>
<p class="lead">The CSV format for Stock data is(filename should be same as Ticker): [Date,ClosingPrice,Volume]</p>
<form method="POST" enctype="multipart/form-data" action="{% url 'stocksapp:upload_csv' %}" id="upload-form">
	<div class="form-group">
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" value="Upload" class="btn btn-primary mb-2">
	</div>

</form>
{% endblock %}